version: '3.8'
services:
  db:
    image: postgres:15
    container_name: fabmanage_postgres_db
    restart: always
    environment:
      POSTGRES_USER: fabmanage_user
      POSTGRES_PASSWORD: fabmanage_pass
      POSTGRES_DB: fabmanage_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:



