services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ../backend:/srv/app
      - /srv/app/node_modules

