services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend.dev
    ports:
      - "5173:5173"
    volumes:
      - ../FabManageNew:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    environment:
      - NODE_ENV=development
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ../backend:/srv/app
      - /srv/app/node_modules
