version: '3.8'

services:
  # Development service
  fabmanage-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_API_BASE_URL=http://fabmanage:3001
    command: npm run dev
    profiles:
      - dev

  # Production service
  fabmanage-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_API_BASE_URL=http://fabmanage:3001
    profiles:
      - prod

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - fabmanage-prod
    profiles:
      - prod

  # PostgreSQL database (optional, for local development)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fabmanage
      POSTGRES_USER: fabmanage
      POSTGRES_PASSWORD: fabmanage123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - dev

volumes:
  postgres_data:
