// Generated from Figma design tokens
// Do not edit this file directly - regenerate using npm run tokens:process

export const designTokens = {
  colors: {
    foreground: {
      primary: "#f2f2f2", // Dark mode foreground primary
      secondary: "#262626", // Dark mode foreground secondary
      accent: "#fafafa", // Same for both modes
      destructive: "#7f1d1d", // Same for both modes
      default: "#fafafa", // Same for both modes
      disabled: "#4d4d4d", // Dark mode foreground disabled
      success: "#059669", // Same for both modes
      muted: "#666666", // Dark mode foreground muted
      warning: "#ca8a04", // Same for both modes
    },
    background: {
      primary: "#151515", // Dark mode background primary
      secondary: "#1a1a1a", // Dark mode background secondary
      muted: "#1a1a1a", // Dark mode background muted
      accent: "#27272a", // Dark mode background accent
      destructive: "#991b1b", // Same for both modes
      success: "#065f46", // Same for both modes
      disabled: "#a3a3a3", // Same for both modes
      default: "#09090b", // Dark mode background default
      card: "#141414", // Dark mode background card
      popover: "#1f1f1f", // Dark mode background popover
      input: "#262626", // Dark mode background input
      warning: "#ea580c", // Same for both modes
    },
    border: {
      primary: "#333333", // Dark mode border primary
      destructive: "#7f1d1d", // Same for both modes
      success: "#059669", // Same for both modes
      default: "#404040", // Dark mode border default
      warning: "#ca8a04", // Same for both modes
    },
    chart: {
      "chart-1": {
        opacity100: "#2662d9ff",
        opacity50: "#2662d980",
        opacity10: "#2662d91a",
        opacity80: "#2662d9cc",
      },
      "chart-2": {
        opacity100: "#e23670ff",
        opacity80: "#e23670ff",
        opacity50: "#e23670ff",
        opacity10: "#e23670ff",
      },
      "chart-3": {
        opacity100: "#e88c30ff",
        opacity80: "#e88c30ff",
        opacity50: "#e88c30ff",
        opacity10: "#e88c30ff",
      },
      "chart-4": {
        opacity100: "#af57dbff",
        opacity80: "#af57dbff",
        opacity50: "#af57dbff",
        opacity10: "#af57dbff",
      },
      "chart-5": {
        opacity100: "#2eb88aff",
        opacity80: "#2eb88aff",
        opacity50: "#2eb88aff",
        opacity10: "#2eb88aff",
      },
    },
    icon: {
      primary: "#e6e6e6", // Dark mode icon primary
      secondary: "#999999", // Dark mode icon secondary
      destructive: "#7f1d1d", // Same for both modes
      success: "#059669", // Same for both modes
      warning: "#ca8a04", // Same for both modes
      disabled: "#525252", // Dark mode icon disabled
      default: "#fafafa", // Same for both modes
      muted: "#666666", // Dark mode icon muted
      accent: "#fafafa", // Same for both modes
    },
    sidebar: {
      DEFAULT: "#141414",
      foreground: "#fafafa",
      primary: "#f2f2f2",
      "primary-foreground": "#18181b",
      accent: "#27272a",
      "accent-foreground": "#fafafa",
      border: "#3f3f46",
      ring: "#fafafa",
    },
  },
  spacing: {
    none: "0px",
    xxs: "2px",
    xs: "4px",
    sm: "8px",
    md: "12px",
    lg: "16px",
    xl: "24px",
    xxl: "32px",
    "3xl": "40px",
    "4xl": "40px",
  },
  padding: {
    none: "0px",
    xxs: "8px",
    xs: "12px",
    sm: "16px",
    md: "20px",
    lg: "24px",
    xl: "32px",
    xxl: "40px",
    "3xl": "48px",
    "4xl": "64px",
  },
  radius: {
    none: "0px",
    xs: "2px",
    sm: "4px",
    md: "8px",
    lg: "12px",
    xl: "16px",
    xxl: "24px",
    full: "400px",
  },
  semantic: {
    primary: "#18181bff",
    secondary: "#f4f4f5ff",
    destructive: "#7f1d1dff",
    success: "#059669ff",
    warning: "#ca8a04ff",
    muted: "#a1a1aaff",
    accent: "#fafafaff",
    card: "#09090bff",
    popover: "#09090bff",
    input: "#3f3f46ff",
    border: "#3f3f46ff",
  },
} as const;

// Type exports
export type ColorToken = keyof typeof designTokens.colors;
export type SpacingToken = keyof typeof designTokens.spacing;
export type RadiusToken = keyof typeof designTokens.radius;

// Semantic color mappings for shadcn/ui
export const semanticColors = designTokens.semantic;
