// Generated from Figma design tokens
// Do not edit this file directly - regenerate using npm run tokens:process

export const designTokens = {
  "colors": {
    "foreground": {
      "primary": "#18181bff",
      "secondary": "#f4f4f5ff",
      "accent": "#fafafaff",
      "destructive": "#7f1d1dff",
      "default": "#fafafaff",
      "disabled": "#52525bff",
      "success": "#059669ff",
      "muted": "#a1a1aaff",
      "warning": "#ca8a04ff"
    },
    "background": {
      "primary": "#fafafaff",
      "secondary": "#27272aff",
      "muted": "#27272aff",
      "accent": "#27272aff",
      "destructive": "#991b1bff",
      "success": "#065f46ff",
      "disabled": "#a3a3a3ff",
      "default": "#09090bff",
      "card": "#09090bff",
      "popover": "#09090bff",
      "input": "#3f3f46ff",
      "warning": "#eab308ff"
    },
    "border": {
      "primary": "#d4d4d8ff",
      "destructive": "#7f1d1dff",
      "success": "#059669ff",
      "default": "#3f3f46ff",
      "warning": "#ca8a04ff"
    },
    "chart": {
      "chart-1": {
        "opacity100": "#2662d9ff",
        "opacity50": "#2662d980",
        "opacity10": "#2662d91a",
        "opacity80": "#2662d9cc"
      },
      "chart-2": {
        "opacity100": "#e23670ff",
        "opacity80": "#e23670ff",
        "opacity50": "#e23670ff",
        "opacity10": "#e23670ff"
      },
      "chart-3": {
        "opacity100": "#e88c30ff",
        "opacity80": "#e88c30ff",
        "opacity50": "#e88c30ff",
        "opacity10": "#e88c30ff"
      },
      "chart-4": {
        "opacity100": "#af57dbff",
        "opacity80": "#af57dbff",
        "opacity50": "#af57dbff",
        "opacity10": "#af57dbff"
      },
      "chart-5": {
        "opacity100": "#2eb88aff",
        "opacity80": "#2eb88aff",
        "opacity50": "#2eb88aff",
        "opacity10": "#2eb88aff"
      }
    },
    "icon": {
      "primary": "#18181bff",
      "secondary": "#f4f4f5ff",
      "destructive": "#7f1d1dff",
      "success": "#059669ff",
      "warning": "#ca8a04ff",
      "disabled": "#52525bff",
      "default": "#fafafaff",
      "muted": "#a1a1aaff",
      "accent": "#fafafaff"
    },
    "sidebar": {
      "DEFAULT": "#141414",
      "foreground": "#fafafa",
      "primary": "#f2f2f2",
      "primary-foreground": "#18181b",
      "accent": "#27272a",
      "accent-foreground": "#fafafa",
      "border": "#3f3f46",
      "ring": "#fafafa"
    }
  },
  "spacing": {
    "none": "0px",
    "xxs": "2px",
    "xs": "4px",
    "sm": "8px",
    "md": "12px",
    "lg": "16px",
    "xl": "24px",
    "xxl": "32px",
    "3xl": "40px",
    "4xl": "40px"
  },
  "padding": {
    "none": "0px",
    "xxs": "8px",
    "xs": "12px",
    "sm": "16px",
    "md": "20px",
    "lg": "24px",
    "xl": "32px",
    "xxl": "40px",
    "3xl": "48px",
    "4xl": "64px"
  },
  "radius": {
    "none": "0px",
    "xs": "2px",
    "sm": "4px",
    "md": "8px",
    "lg": "12px",
    "xl": "16px",
    "xxl": "24px",
    "full": "400px"
  },
  "semantic": {
    "primary": "#18181bff",
    "secondary": "#f4f4f5ff",
    "destructive": "#7f1d1dff",
    "success": "#059669ff",
    "warning": "#ca8a04ff",
    "muted": "#a1a1aaff",
    "accent": "#fafafaff",
    "card": "#09090bff",
    "popover": "#09090bff",
    "input": "#3f3f46ff",
    "border": "#3f3f46ff"
  }
} as const;

// Type exports
export type ColorToken = keyof typeof designTokens.colors;
export type SpacingToken = keyof typeof designTokens.spacing;
export type RadiusToken = keyof typeof designTokens.radius;

// Semantic color mappings for shadcn/ui
export const semanticColors = designTokens.semantic;
